const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const DEPOSIT = "DEPOSIT";
const WITHDRAW = "WITHDRAW";

export { INCREMENT, DECREMENT, LOGIN, LOGOUT, DEPOSIT, WITHDRAW };
